In [7]:
# importing Libraries

In [8]:
import pandas as pd

In [9]:
import numpy as np

In [10]:
# Loading Dataset

In [11]:
df=pd.read_csv("/content/drive/MyDrive/dirty_data.csv")

In [12]:
df.head()

,Order ID,consumer_first_class,consumer_same_day,consumer_second_class,consumer_standard_class,consumer_total,corporate_first_class,corporate_same_day,corporate_second_class,corporate_standard_class,corporate_total,home_office_first_class,home_office_same_day,home_office_second_class,home_office_standard_class,home_office_total
0,CA-2011-100293,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91.056,91.056
1,CA-2011-100706,NaN,NaN,129.44,NaN,129.44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CA-2011-100895,NaN,NaN,NaN,605.47,605.47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CA-2011-100916,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,788.86,788.86,NaN,NaN,NaN,NaN,NaN
4,CA-2011-101266,NaN,NaN,13.36,NaN,13.36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
# Initial Exploration

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 823 entries, 0 to 822
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Order ID                    823 non-null    object
 1   consumer_first_class        73 non-null     float64
 2   consumer_same_day           29 non-null     float64
 3   consumer_second_class       92 non-null     float64
 4   consumer_standard_class     254 non-null    float64
 5   consumer_total              445 non-null    float64
 6   corporate_first_class       41 non-null     float64
 7   corporate_same_day          6 non-null      float64
 8   corporate_second_class      51 non-null     float64
 9   corporate_standard_class    153 non-null    float64
 10  corporate_total             248 non-null    float64
 11  home_office_first_class     13 non-null     float64
 12  home_office_same_day        7 non-null      float64
 13  home_office_second_class    24 non-null     float64
 14  home_office_standard_class  91 non-null     float64
 15  home_office_total           132 non-null    float64
dtypes: float64(15), object(1)
memory usage: 103.0+ KB

In [14]:
df.shape

(823, 16)

In [15]:
df.describe()

,consumer_first_class,consumer_same_day,consumer_second_class,consumer_standard_class,consumer_total,corporate_first_class,corporate_same_day,corporate_second_class,corporate_standard_class,corporate_total,home_office_first_class,home_office_same_day,home_office_second_class,home_office_standard_class,home_office_total
count,73.000000,29.000000,92.000000,254.000000,445.000000,41.000000,6.00000,51.000000,153.000000,248.000000,13.000000,7.000000,24.000000,91.000000,132.000000
mean,569.922548,560.855793,1080.962054,920.646728,879.015600,1014.273512,3302.43600,1382.087490,731.278255,982.951069,1190.428615,850.701714,732.593917,1203.266648,1125.075780
std,2440.803261,1502.242037,5255.130764,7346.221367,9285.318749,3256.300926,4484.72925,4930.601791,4543.001377,7761.266452,2175.118083,1177.706403,1759.042386,6206.566900,6753.344616
min,2.214000,10.272000,2.064000,2.610000,2.064000,2.896000,111.90400,3.760000,1.167000,1.167000,3.744000,7.968000,3.444000,3.760000,3.444000
25%,34.200000,36.192000,32.005500,41.947000,36.192000,47.320000,276.53850,25.950000,30.336000,31.066500,121.780000,186.794000,62.554000,32.914000,35.820000
50%,88.920000,107.830000,181.911000,183.870000,173.940000,242.546000,734.63700,342.240000,106.944000,158.252000,220.056000,259.290000,221.821500,141.960000,150.060000
75%,348.560000,354.900000,714.023875,549.543000,517.500000,670.001000,6335.37750,1129.897000,364.930000,583.518500,771.800000,1168.305000,754.517500,492.287000,530.497500
max,20802.173000,8132.409000,49724.254500,116922.134500,195580.971000,20792.607000,9907.30800,35243.231000,55942.786500,121885.932500,7737.786000,2977.456000,8791.127000,54748.632500,74255.001500

In [20]:
# Data Quality Report

In [17]:
# Missing Values
missing = pd.DataFrame({
    "Missing Count": df.isnull().sum(),
    "Missing Percentage": round(df.isnull().mean()*100,2)
})

missing

                            Missing Count  Missing Percentage
Order ID                                0                0.00
consumer_first_class                  750               91.13
consumer_same_day                     794               96.48
consumer_second_class                 731               88.82
consumer_standard_class               569               69.14
consumer_total                        378               45.93
corporate_first_class                 782               95.02
corporate_same_day                    817               99.27
corporate_second_class                772               93.80
corporate_standard_class              670               81.41
corporate_total                       575               69.87
home_office_first_class               810               98.42
home_office_same_day                  816               99.15
home_office_second_class              799               97.08
home_office_standard_class            732               88.94
home_office_total                     691               83.96

In [18]:
# Duplicate Rows
duplicates = df.duplicated().sum()
print("Duplicate Rows:", duplicates)

Duplicate Rows: 0

In [19]:
# Data Types
print(df.dtypes)

Order ID                       object
consumer_first_class          float64
consumer_same_day             float64
consumer_second_class         float64
consumer_standard_class       float64
consumer_total                float64
corporate_first_class         float64
corporate_same_day            float64
corporate_second_class        float64
corporate_standard_class      float64
corporate_total               float64
home_office_first_class       float64
home_office_same_day          float64
home_office_second_class      float64
home_office_standard_class    float64
home_office_total             float64
dtype: object

In [22]:
### Data Quality Report

# Dataset contains 823 rows and 16 columns.
# Order ID has no missing values.
# Numeric columns contain a large number of missing values.
# No duplicate rows found (verify using duplicated()).
# Order ID is stored as object.

In [23]:
# Missing Value Handling

In [25]:
# Filling missing numeric values with 0
numeric_cols = df.select_dtypes(include='number').columns

df[numeric_cols] = df[numeric_cols].fillna(0)

In [28]:
# verifying

In [26]:
df.isnull().sum()

Order ID                      0
consumer_first_class          0
consumer_same_day             0
consumer_second_class         0
consumer_standard_class       0
consumer_total                0
corporate_first_class         0
corporate_same_day            0
corporate_second_class        0
corporate_standard_class      0
corporate_total               0
home_office_first_class       0
home_office_same_day          0
home_office_second_class      0
home_office_standard_class    0
home_office_total             0
dtype: int64

In [27]:

# Missing values were replaced with 0 because blank values indicate that no shipment/value exists for that shipping mode.
# Using mean or median would introduce incorrect values.

In [29]:
# Duplicate Removal

In [30]:
before_rows = df.shape[0]

df = df.drop_duplicates()

after_rows = df.shape[0]

print("Rows Removed:", before_rows - after_rows)

Rows Removed: 0

In [31]:
# Standardization

In [32]:
df.columns = df.columns.str.lower().str.strip().str.replace(" ","_")

In [33]:
df["order_id"] = df["order_id"].astype(str)

In [34]:
# Outlier Detection

In [35]:
numeric = df.select_dtypes(include=np.number)

for col in numeric.columns:

    Q1 = df[col].quantile(0.25)

    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5*IQR

    upper = Q3 + 1.5*IQR

    outliers = df[(df[col] < lower) | (df[col] > upper)]

    print(col, ":", len(outliers))

consumer_first_class : 73
consumer_same_day : 29
consumer_second_class : 92
consumer_standard_class : 169
consumer_total : 119
corporate_first_class : 41
corporate_same_day : 6
corporate_second_class : 51
corporate_standard_class : 153
corporate_total : 175
home_office_first_class : 13
home_office_same_day : 7
home_office_second_class : 24
home_office_standard_class : 91
home_office_total : 132

In [36]:
# Cap Outliers

In [37]:
for col in numeric.columns:

    Q1 = df[col].quantile(0.25)

    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5*IQR

    upper = Q3 + 1.5*IQR

    df[col] = df[col].clip(lower, upper)

In [38]:
# Data Type Correction

In [39]:
df["order_id"] = df["order_id"].astype(str)

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 823 entries, 0 to 822
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   order_id                    823 non-null    object
 1   consumer_first_class        823 non-null    float64
 2   consumer_same_day           823 non-null    float64
 3   consumer_second_class       823 non-null    float64
 4   consumer_standard_class     823 non-null    float64
 5   consumer_total              823 non-null    float64
 6   corporate_first_class       823 non-null    float64
 7   corporate_same_day          823 non-null    float64
 8   corporate_second_class      823 non-null    float64
 9   corporate_standard_class    823 non-null    float64
 10  corporate_total             823 non-null    float64
 11  home_office_first_class     823 non-null    float64
 12  home_office_same_day        823 non-null    float64
 13  home_office_second_class    823 non-null    float64
 14  home_office_standard_class  823 non-null    float64
 15  home_office_total           823 non-null    float64
dtypes: float64(15), object(1)
memory usage: 103.0+ KB

In [41]:
# Before vs After Summary

In [42]:
summary = pd.DataFrame({

'Metric':[
'Rows Before',
'Rows After',
'Duplicate Rows Removed',
'Remaining Missing Values'
],

'Value':[

823,

len(df),

before_rows-after_rows,

df.isnull().sum().sum()

]

})

summary

                     Metric  Value
0               Rows Before    823
1                Rows After    823
2    Duplicate Rows Removed      0
3  Remaining Missing Values      0

In [43]:
# Saving Cleaned Dataset

In [44]:
df.to_csv("cleaned_dataset.csv", index=False)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.

In [45]:
df=pd.read_csv("/content/cleaned_dataset.csv")

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 823 entries, 0 to 822
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   order_id                    823 non-null    object
 1   consumer_first_class        823 non-null    float64
 2   consumer_same_day           823 non-null    float64
 3   consumer_second_class       823 non-null    float64
 4   consumer_standard_class     823 non-null    float64
 5   consumer_total              823 non-null    float64
 6   corporate_first_class       823 non-null    float64
 7   corporate_same_day          823 non-null    float64
 8   corporate_second_class      823 non-null    float64
 9   corporate_standard_class    823 non-null    float64
 10  corporate_total             823 non-null    float64
 11  home_office_first_class     823 non-null    float64
 12  home_office_same_day        823 non-null    float64
 13  home_office_second_class    823 non-null    float64
 14  home_office_standard_class  823 non-null    float64
 15  home_office_total           823 non-null    float64
dtypes: float64(15), object(1)
memory usage: 103.0+ KB

In [48]:
## Conclusion

# 1. Dataset loaded successfully.
# 2. Data quality report generated.
# 3. Missing values replaced with 0.
# 4. Duplicate rows checked .
# 5. Column names standardized.
# 6. Outliers detected using IQR and capped.
# 7. Data types verified.
# 8. Before vs After summary prepared.
# 9. Cleaned dataset exported as cleaned_dataset.csv.